name: spk_water_quality_fuzzyahp_ta
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  intl: ^0.18.1
  syncfusion_flutter_gauges: ^26.1.35
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  http: ^1.2.1
  package_info_plus: ^8.0.0
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"